In [14]:
# use the model in Model, and dataloader in Dataloaders
# to train the model
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from Models import mobilenetv2
from Dataloaders import dataloader_cifar10
import os
import numpy as np
import matplotlib.pyplot as plt

# get the dataset
train, test, labels = dataloader_cifar10.Dataloader_cifar10(train_batch=128, test_batch=100, seed=2024)

# 2. transfer the dataset to fit the model, for the training, client and server model are all on the server
client_model, server_model = mobilenetv2.stupid_model_splitter(weight_path='/home/tonypeng/Workspace1/adaptfilter/Adaptfilter/otherwork/pytorchcifar/checkpoint/MobileNetV2.pth')
net = mobilenetv2.MobileNetV2()
net.load_state_dict(torch.load('/home/tonypeng/Workspace1/adaptfilter/Adaptfilter/otherwork/pytorchcifar/checkpoint/MobileNetV2.pth')['net'])

# gating = some_gating_function()

# reducer = some_reducer_funtion()

# generator = some_generator_funtion()

client_model = client_model.cuda()
server_model = server_model.cuda()
net = net.cuda()

# test the model
client_model.eval()
server_model.eval()
net.eval()

with torch.no_grad():
    for i, (data, target) in enumerate(train):
        data, target = data.cuda(), target.cuda()
        output = client_model(data)
        output = server_model(output)
        output2 = net(data)
        # get the argmax
        _, predicted = output.max(1)
        _, predicted2 = output2.max(1)
        print(predicted)
        print(predicted2)
        print(target)   
        print(target - predicted2)
        break


Files already downloaded and verified
Files already downloaded and verified
tensor([7, 7, 7, 3, 2, 3, 1, 7, 6, 4, 5, 6, 2, 9, 4, 3, 3, 5, 0, 6, 8, 2, 2, 6,
        5, 4, 3, 9, 8, 9, 2, 8, 2, 9, 4, 5, 3, 4, 5, 8, 8, 0, 7, 9, 1, 1, 3, 9,
        1, 8, 7, 5, 0, 7, 7, 6, 4, 1, 5, 7, 3, 8, 4, 8, 1, 5, 5, 1, 6, 1, 8, 0,
        1, 0, 9, 6, 6, 9, 7, 9, 5, 2, 6, 4, 9, 2, 6, 0, 0, 3, 4, 1, 7, 7, 3, 3,
        9, 0, 1, 7, 4, 8, 9, 3, 0, 4, 8, 2, 0, 1, 1, 5, 4, 2, 6, 0, 4, 9, 9, 6,
        8, 1, 3, 2, 1, 7, 8, 7], device='cuda:0')
tensor([7, 7, 7, 3, 2, 3, 1, 7, 6, 4, 5, 6, 2, 9, 4, 3, 3, 5, 0, 6, 8, 2, 2, 6,
        5, 4, 3, 9, 8, 9, 2, 8, 2, 9, 4, 5, 3, 4, 5, 8, 8, 0, 7, 9, 1, 1, 3, 9,
        1, 8, 7, 5, 0, 7, 7, 6, 4, 1, 5, 7, 3, 8, 4, 8, 1, 5, 5, 1, 6, 1, 8, 0,
        1, 0, 9, 6, 6, 9, 7, 9, 5, 2, 6, 4, 9, 2, 6, 0, 0, 3, 4, 1, 7, 7, 3, 3,
        9, 0, 1, 7, 4, 8, 9, 3, 0, 4, 8, 2, 0, 1, 1, 5, 4, 2, 6, 0, 4, 9, 9, 6,
        8, 1, 3, 2, 1, 7, 8, 7], device='cuda:0')
tensor([7, 7, 7, 5, 2, 3